name: Release

on: { push: { tags: 'v[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating a GitHub release
      id-token: write # for publishing to npm with provenance
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with: { ref: 'main' } # attach HEAD to 'main'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with: { version: latest }

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with: { node-version: latest, cache: pnpm, registry-url: https://registry.npmjs.org }

      - name: Set env variables
        run: echo -e ZIP=ZIP=${GITHUB_REPOSITORY#*/}-$TAG.zip >> $GITHUB_ENV

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build:prod

      - name: Lint
        run: pnpm lint

      - name: Create release archive
        run: zip -r $ZIP package.json LICENSE README.md dist

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $TAG --title $TAG --draft $ZIP

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --provenance